# Generated by Django 4.2.7 on 2026-01-16 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='travelsprofile',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelsprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelsprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='travelsprofile',
            name='company_name',
            field=models.CharField(default='Ritham Tours & Travels', max_length=255),
        ),
        migrations.AlterField(
            model_name='travelsprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('travels', 'Travels Admin')], default='customer', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customerprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='travelsprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_payments_enabled', models.BooleanField(default=True, help_text='Enable/disable UPI payment option on booking page')),
                ('razorpay_enabled', models.BooleanField(default=True, help_text='Enable/disable Razorpay online payments')),
                ('default_payment_method', models.CharField(choices=[('upi', 'UPI Payment'), ('driver', 'Pay Driver'), ('office', 'Pay at Office')], default='driver', help_text='Default payment method when UPI is disabled', max_length=20)),
                ('advance_payment_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage of total amount for advance payment', max_digits=5)),
                ('booking_cancellation_enabled', models.BooleanField(default=True, help_text='Allow customers to cancel bookings')),
                ('auto_booking_confirmation', models.BooleanField(default=False, help_text='Automatically confirm bookings without admin approval')),
                ('sms_notifications_enabled', models.BooleanField(default=True, help_text='Send SMS notifications for booking updates')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Send email notifications for booking updates')),
                ('whatsapp_notifications_enabled', models.BooleanField(default=True, help_text='Send WhatsApp notifications for booking updates')),
                ('gst_enabled', models.BooleanField(default=True, help_text='Apply GST to bookings')),
                ('hill_station_charges_enabled', models.BooleanField(default=True, help_text='Apply hill station charges to applicable destinations')),
                ('dynamic_pricing_enabled', models.BooleanField(default=False, help_text='Enable dynamic pricing based on demand and season')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Put website in maintenance mode')),
                ('online_booking_enabled', models.BooleanField(default=True, help_text='Allow online bookings (disable for phone-only bookings)')),
                ('show_vehicle_images', models.BooleanField(default=True, help_text='Display vehicle images on booking page')),
                ('primary_phone', models.CharField(default='+91 97871 10763', help_text='Primary contact phone number', max_length=15)),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary contact phone number', max_length=15)),
                ('email_address', models.EmailField(default='rithamtravels@gmail.com', help_text='Primary contact email address', max_length=254)),
                ('whatsapp_number', models.CharField(default='+91 97871 10763', help_text='WhatsApp contact number', max_length=15)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/share/1G4KuLPscB/', help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/rithamtoursandtravels', help_text='Instagram profile URL')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/@rithamtoursandtravels?si=rJulxr_AG9qUCaqI', help_text='YouTube channel URL')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/krishna-moorthy-9879689b/?originalSubdomain=in', help_text='LinkedIn profile URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
