# Generated by Django 4.2.7 on 2026-01-16 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_otp', models.CharField(max_length=6)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'is_used', 'expires_at'], name='accounts_pa_user_id_cad790_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['created_at'], name='accounts_pa_created_2b9495_idx'),
        ),
        migrations.AddField(
            model_name='otpattemptlog',
            name='otp_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.passwordresetotp'),
        ),
        migrations.AddField(
            model_name='otpattemptlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otpattemptlog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ot_user_id_e6c20c_idx'),
        ),
        migrations.AddIndex(
            model_name='otpattemptlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='accounts_ot_ip_addr_c23fef_idx'),
        ),
    ]
