# Generated by Django 4.2.7 on 2026-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpattemptlog_passwordresetotp_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='upi_payments_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable UPI payment option on booking page'),
        ),
    ]
