# Generated by Django 4.2.7 on 2026-01-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_gst_default'),
        ('accounts', '0005_update_upi_default'),
    ]

    operations = [
    ]
