# Generated by Django 4.2.7 on 2025-12-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_packages/')),
                ('days', models.IntegerField(choices=[(1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days'), (6, '6 Days'), (7, '7 Days'), (8, '8 Days')])),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_vehicle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cities', models.ManyToManyField(related_name='tour_packages', to='tours.city')),
            ],
            options={
                'db_table': 'tour_packages',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_type', models.CharField(choices=[('local_hour', 'Local Tariff - Hour Basis'), ('outstation_day', 'Out Station - Day Basis'), ('outstation_km', 'Out Station - Km Basis'), ('oneway_fixed', 'One Way Dropping (Fixed)'), ('oneway_km', 'One Way Dropping (Km Basis)')], max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_hours', models.IntegerField(blank=True, default=4, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='tours.city')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'tariffs',
            },
        ),
        migrations.CreateModel(
            name='SightseeingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sightseeing/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightseeing_spots', to='tours.city')),
            ],
            options={
                'db_table': 'sightseeing_spots',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_way_fixed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='tours.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='tours.city')),
            ],
            options={
                'db_table': 'routes',
                'unique_together': {('from_city', 'to_city')},
            },
        ),
        migrations.CreateModel(
            name='LocalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_areas', to='tours.city')),
            ],
            options={
                'db_table': 'local_areas',
                'unique_together': {('city', 'name')},
            },
        ),
    ]
