# Generated by Django 4.2.7 on 2025-12-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_city_latitude_city_longitude_localarea_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sightseeing_kilometers',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total sightseeing distance in kilometers', max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='tourist_places',
            field=models.TextField(blank=True, help_text='Enter tourist places separated by commas', null=True),
        ),
    ]
