# Generated by Django 4.2.7 on 2025-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_add_sightseeing_fields_to_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='hotel_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
