# Generated by Django 4.2.7 on 2025-12-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourpackage_hotel_info_tourpackage_itinerary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='day_wise_itinerary',
            field=models.JSONField(blank=True, help_text='Day-wise tour plan - [{day, pickup_time, pickup_location, places_to_visit, route_description, notes}]', null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='hotel_details',
            field=models.JSONField(blank=True, help_text='Hotel booking details - {name, city, checkin, checkout, room_type}', null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='include_hotel',
            field=models.BooleanField(default=False, help_text='Include hotel booking in package'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='pickup_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_packages', to='tours.city'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Recommended vehicle type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='days',
            field=models.IntegerField(choices=[(1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days'), (6, '6 Days'), (7, '7 Days'), (8, '8 Days'), (9, '9 Days'), (10, '10 Days'), (11, '11 Days'), (12, '12 Days'), (13, '13 Days'), (14, '14 Days'), (15, '15 Days')]),
        ),
    ]
