# Generated by Django 4.2.7 on 2026-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tourpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hill_station_charge',
            field=models.DecimalField(decimal_places=2, default=750.0, help_text='Hill station charge per visit', max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='is_hill_station',
            field=models.BooleanField(default=False, help_text='Mark as true if this is a hill station (charges Rs. 750 per visit)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='days',
            field=models.IntegerField(choices=[(1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days')]),
        ),
    ]
