# Generated by Django 4.2.7 on 2025-12-20 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0002_add_user_to_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to=settings.AUTH_USER_MODEL),
        ),
    ]
