# Generated by Django 4.2.7 on 2025-12-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('fare_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_charge_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_km_per_day', models.IntegerField(default=250)),
                ('max_seats', models.IntegerField(default=4)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['fare_per_km'],
            },
        ),
    ]
