# Generated by Django 4.2.7 on 2025-12-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ac_type',
            field=models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], default='ac', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show in listings'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='luggage_capacity',
            field=models.CharField(blank=True, help_text='e.g., 2 Large + 2 Small', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_charge_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fare_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_seats',
            field=models.IntegerField(default=4, help_text='Maximum passenger seats (excluding driver)'),
        ),
        migrations.CreateModel(
            name='VehicleTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('oneway', 'One Way Drop'), ('round_trip', 'Round Trip'), ('outstation', 'Out Station'), ('local', 'Local Trip')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('night_charge', models.DecimalField(decimal_places=2, default=0, help_text='Additional charge for night trips', max_digits=10)),
                ('toll_charges', models.BooleanField(default=True, help_text='Toll charges applicable')),
                ('min_km', models.IntegerField(default=0, help_text='Minimum kilometers')),
                ('min_hours', models.IntegerField(default=0, help_text='Minimum hours')),
                ('min_days', models.IntegerField(default=1, help_text='Minimum days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_tariffs', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_tariffs',
                'ordering': ['vehicle', 'trip_type'],
                'unique_together': {('vehicle', 'trip_type')},
            },
        ),
    ]
