# Generated by Django 4.2.7 on 2025-12-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_ac_type_vehicle_fuel_type_vehicle_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='per_day_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vehicle per day fee', max_digits=10),
        ),
    ]
