# Generated by Django 4.2.7 on 2025-12-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_per_day_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fare_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate for local trips', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_distance_min_hours',
            field=models.IntegerField(default=30, help_text='Maximum distance covered in minimum hours'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_hours_fee_local',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum hours fee for local trips', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_hours_local',
            field=models.IntegerField(default=3, help_text='Minimum hours for local trips'),
        ),
    ]
