# Generated by Django 4.2.7 on 2025-12-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_fare_per_hour_vehicle_max_distance_min_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fare_per_km_local',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra KM rate for local trips when distance exceeds included KM', max_digits=10),
        ),
    ]
