# Generated by Django 4.2.7 on 2025-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
