# Generated by Django 4.2.7 on 2025-12-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('outstation', 'Out Station'), ('local', 'Local'), ('oneway', 'One Way'), ('tour', 'Tour Package'), ('multicity', 'Multi City'), ('online_cab', 'Online Cab Booking')], max_length=20),
        ),
    ]
