# Generated by Django 4.2.7 on 2026-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_trip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('transport', 'Transport Services'), ('accommodation', 'Accommodation'), ('tour_package', 'Tour Package'), ('general', 'General Services')], default='transport', max_length=50)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Rate',
                'verbose_name_plural': 'GST Rates',
                'db_table': 'gst_rates',
                'ordering': ['-effective_from'],
            },
        ),
    ]
