# Generated by Django 4.2.7 on 2025-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(help_text="URL path (e.g., '/about/', '/tours/goa/')", max_length=255, unique=True)),
                ('page_name', models.CharField(help_text='Human-readable page name for admin', max_length=100)),
                ('page_type', models.CharField(choices=[('website', 'Website'), ('article', 'Article'), ('blog', 'Blog Post'), ('product', 'Product'), ('tour', 'Tour Package'), ('contact', 'Contact Page'), ('about', 'About Page'), ('service', 'Service Page')], default='website', help_text='Page type for structured data', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Page title (max 60 characters, leave blank to use default)', max_length=60)),
                ('description', models.TextField(blank=True, help_text='Meta description (max 160 characters, leave blank to use default)', max_length=160)),
                ('keywords', models.TextField(blank=True, help_text='Page-specific keywords (comma-separated, leave blank to use default)')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use page title)', max_length=60)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (leave blank to use meta description)', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og_images/')),
                ('og_image_alt', models.CharField(blank=True, help_text='Alt text for Open Graph image', max_length=100)),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter Card type', max_length=20)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL (leave blank to use current page URL)')),
                ('robots', models.CharField(default='index, follow', help_text='Robots meta tag content', max_length=50)),
                ('schema_type', models.CharField(blank=True, help_text="Schema.org type (e.g., 'LocalBusiness', 'Article')", max_length=50)),
                ('article_section', models.CharField(blank=True, help_text='Article section (for blog posts)', max_length=50)),
                ('published_time', models.DateTimeField(blank=True, help_text='Article published time', null=True)),
                ('modified_time', models.DateTimeField(blank=True, help_text='Article modified time', null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price (for tour packages)', max_digits=10, null=True)),
                ('product_currency', models.CharField(default='INR', help_text='Product currency code', max_length=3)),
                ('product_availability', models.CharField(default='https://schema.org/InStock', help_text='Product availability status', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Enable SEO overrides for this page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO Overrides',
                'ordering': ['page_path'],
            },
        ),
        migrations.CreateModel(
            name='SEOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ritham Tours & Travels', help_text='Site name used in titles and meta tags', max_length=100)),
                ('site_description', models.TextField(default='Professional travel agency offering tours, cab bookings, and travel packages across India. Your trusted travel partner for memorable experiences.', help_text='Default site description (max 160 characters)', max_length=160)),
                ('site_keywords', models.TextField(default='tours, travel, cab booking, tour packages, ritham tours, travel agency, india tours', help_text='Default site keywords (comma-separated)')),
                ('facebook_app_id', models.CharField(blank=True, help_text='Facebook App ID for Open Graph', max_length=50)),
                ('twitter_handle', models.CharField(default='@rithamtravels', help_text='Twitter handle (include @)', max_length=50)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (GA4)', max_length=50)),
                ('google_site_verification', models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100)),
                ('default_og_image', models.ImageField(blank=True, help_text='Default Open Graph image (1200x630px recommended)', null=True, upload_to='seo/og_images/')),
                ('robots_txt_content', models.TextField(blank=True, help_text='Custom robots.txt content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Mark as active to use this configuration')),
            ],
            options={
                'verbose_name': 'SEO Configuration',
                'verbose_name_plural': 'SEO Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SEORedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Old URL path to redirect from', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='New URL path to redirect to', max_length=255)),
                ('redirect_type', models.CharField(choices=[('301', 'Permanent (301)'), ('302', 'Temporary (302)')], default='301', help_text='Type of redirect', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Enable this redirect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Redirect',
                'verbose_name_plural': 'SEO Redirects',
                'ordering': ['old_path'],
            },
        ),
    ]
